# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=models.TextField(),
        ),
    ]
